package com.ak.eventapi.db.domain;
// Generated 02-Mar-2020 14:37:19 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppRole generated by hbm2java
 */
@Entity
@Table(name = "app_role")
public class RoleEntity implements java.io.Serializable {

	private Integer id;
	private String description;
	private String roleName;
	private Set<UserRoleEntity> userRoles = new HashSet<UserRoleEntity>(0);

	public RoleEntity() {
	}

	public RoleEntity(String description, String roleName, Set<UserRoleEntity> userRoles) {
		this.description = description;
		this.roleName = roleName;
		this.userRoles = userRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "role_name")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appRole")
	public Set<UserRoleEntity> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRoleEntity> userRoles) {
		this.userRoles = userRoles;
	}

}
