package com.ak.eventapi.db.domain;
// Generated 02-Mar-2020 14:37:19 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name = "app_user")
public class UserEntity implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String password;
	private String username;
	private Set<UserRoleEntity> userRoles = new HashSet<UserRoleEntity>(0);

	public UserEntity() {
	}

	public UserEntity(String firstName, String lastName, String password, String username) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.username = username;
	}

	public UserEntity(String firstName, String lastName, String password, String username, Set<UserRoleEntity> userRoles) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.username = username;
		this.userRoles = userRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUser")
	public Set<UserRoleEntity> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRoleEntity> userRoles) {
		this.userRoles = userRoles;
	}

}
