package com.ak.eventapi.db.domain;
// Generated 02-Mar-2020 14:37:19 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRoleEntity implements java.io.Serializable {

	private UserRoleIdEntity id;
	private RoleEntity appRole;
	private UserEntity appUser;

	public UserRoleEntity() {
	}

	public UserRoleEntity(UserRoleIdEntity id) {
		this.id = id;
	}

	public UserRoleEntity(UserRoleIdEntity id, RoleEntity appRole, UserEntity appUser) {
		this.id = id;
		this.appRole = appRole;
		this.appUser = appUser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "appUser", column = @Column(name = "app_user")),
			@AttributeOverride(name = "appRole", column = @Column(name = "app_role")) })
	public UserRoleIdEntity getId() {
		return this.id;
	}

	public void setId(UserRoleIdEntity id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_role", insertable = false, updatable = false)
	public RoleEntity getAppRole() {
		return this.appRole;
	}

	public void setAppRole(RoleEntity appRole) {
		this.appRole = appRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_user", insertable = false, updatable = false)
	public UserEntity getAppUser() {
		return this.appUser;
	}

	public void setAppUser(UserEntity appUser) {
		this.appUser = appUser;
	}

}
