package com.ak.eventapi.dto;
// Generated 02-Mar-2020 14:36:17 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * AppRole generated by hbm2java
 */
public class RoleDTO implements java.io.Serializable {

	private Integer id;
	private String description;
	private String roleName;
	private Set userRoles = new HashSet(0);

	public RoleDTO() {
	}

	public RoleDTO(String description, String roleName, Set userRoles) {
		this.description = description;
		this.roleName = roleName;
		this.userRoles = userRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
