package com.ak.eventapi.dto;
// Generated 02-Mar-2020 14:36:17 by Hibernate Tools 5.4.7.Final

/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleIdDTO implements java.io.Serializable {

	private Integer appUser;
	private Integer appRole;

	public UserRoleIdDTO() {
	}

	public UserRoleIdDTO(Integer appUser, Integer appRole) {
		this.appUser = appUser;
		this.appRole = appRole;
	}

	public Integer getAppUser() {
		return this.appUser;
	}

	public void setAppUser(Integer appUser) {
		this.appUser = appUser;
	}

	public Integer getAppRole() {
		return this.appRole;
	}

	public void setAppRole(Integer appRole) {
		this.appRole = appRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleIdDTO))
			return false;
		UserRoleIdDTO castOther = (UserRoleIdDTO) other;

		return ((this.getAppUser() == castOther.getAppUser()) || (this.getAppUser() != null
				&& castOther.getAppUser() != null && this.getAppUser().equals(castOther.getAppUser())))
				&& ((this.getAppRole() == castOther.getAppRole()) || (this.getAppRole() != null
						&& castOther.getAppRole() != null && this.getAppRole().equals(castOther.getAppRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAppUser() == null ? 0 : this.getAppUser().hashCode());
		result = 37 * result + (getAppRole() == null ? 0 : this.getAppRole().hashCode());
		return result;
	}

}
