package com.ak.eventapi.dto;
// Generated 02-Mar-2020 14:36:17 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * AppUser generated by hbm2java
 */
public class UserDTO implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String password;
	private String username;
	private Set userRoles = new HashSet(0);

	public UserDTO() {
	}

	public UserDTO(String firstName, String lastName, String password, String username) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.username = username;
	}

	public UserDTO(String firstName, String lastName, String password, String username, Set userRoles) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.username = username;
		this.userRoles = userRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
