package com.ak.eventapi.dto;
// Generated 02-Mar-2020 14:36:17 by Hibernate Tools 5.4.7.Final

/**
 * UserRole generated by hbm2java
 */
public class UserRoleDTO implements java.io.Serializable {

	private UserRoleIdDTO id;
	private RoleDTO appRole;
	private UserDTO appUser;

	public UserRoleDTO() {
	}

	public UserRoleDTO(UserRoleIdDTO id) {
		this.id = id;
	}

	public UserRoleDTO(UserRoleIdDTO id, RoleDTO appRole, UserDTO appUser) {
		this.id = id;
		this.appRole = appRole;
		this.appUser = appUser;
	}

	public UserRoleIdDTO getId() {
		return this.id;
	}

	public void setId(UserRoleIdDTO id) {
		this.id = id;
	}

	public RoleDTO getAppRole() {
		return this.appRole;
	}

	public void setAppRole(RoleDTO appRole) {
		this.appRole = appRole;
	}

	public UserDTO getAppUser() {
		return this.appUser;
	}

	public void setAppUser(UserDTO appUser) {
		this.appUser = appUser;
	}

}
